#! python


def build(ctx):

    # Illustrate simple use of run_py_script
    ctx(
        features='run_py_script',
        source='clean_data.py',
        target=ctx.path_to(ctx, 'OUT_DATA', 'data_clean.csv'),
        name='clean_data'
    )
