#! python


def build(ctx):

    for model in {'baseline'}:

        ctx(
            features='run_py_script',
            source='plot_regressions.py',
            deps=[
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'timing_{}.pickle'.format(model)),
                ctx.path_to(ctx, 'IN_MODEL_SPECS', '{}.json'.format(model))
            ],
            target=ctx.path_to(ctx, 'OUT_FIGURES', 'timing_{}.png'.format(model)),
            append=model,
            name='plot_regressions_{}'.format(model)
        )


    # from src.final.project_dependency_graph import make_project_dependency_graph

    # ctx.add_post_fun(make_project_dependency_graph)
