#! python

import os


def build(ctx):

    for model in {'baseline'}:

        # Illustrate use of run_py_script with automatic model specification.
        ctx(
            features='run_py_script',
            source='timing.py',
            deps=[
                ctx.path_to(ctx, 'OUT_DATA', 'data_clean.csv'),
                ctx.path_to(ctx, 'IN_MODEL_CODE', 'update.py'),
                ctx.path_to(ctx, 'IN_MODEL_SPECS', '{}.json'.format(model)),
            ],
            target=[
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'timing_{}.pickle'.format(model)),
                ctx.path_to(ctx, 'OUT_ANALYSIS', 'log', 'timing_{}.log'.format(model))
            ],
            append=model,
            name='timing_{}'.format(model)
        )

        abspath = os.path.join(ctx.path.abspath(), 'test_update.py')
        ctx(
            features='run_py_script',
            source='test_update.py',
            deps=ctx.path_to(ctx, 'IN_MODEL_CODE', 'update.py'),
            append=abspath
        )
